services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - PYANNOTE_AUTH_TOKEN=${PYANNOTE_AUTH_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SSL_DOMAIN_NAME=${SSL_DOMAIN_NAME}
      - SSL_EMAIL=${SSL_EMAIL}
      - HF_ENDPOINT=https://hf-mirror.com
    volumes:
      - huggingface:/root/.cache/huggingface
      - ./data:/app/data
      - /etc/letsencrypt:/etc/letsencrypt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - app
    restart: always

volumes:
  huggingface:
